### ISSUE TITLE
hello , i need help (compile error)

### ISSUE THREAD

**Issue by gamarorit** [arthurdead/sm-plugins#2]
C:\Users\protr\Desktop\scripting\playermodel.sp(254) : error 100: function prototypes do not match
C:\Users\protr\Desktop\scripting\playermodel.sp(255) : error 100: function prototypes do not match
C:\Users\protr\Desktop\scripting\playermodel.sp(1118) : error 092: number of arguments does not match definition
C:\Users\protr\Desktop\scripting\playermodel.sp(1084) : warning 203: symbol is never used: "SetEntityAlpha"
C:\Users\protr\Desktop\scripting\playermodel.sp(1074) : warning 203: symbol is never used: "GetEntityAlpha"
C:\Users\protr\Desktop\scripting\playermodel.sp(55) : warning 203: symbol is never used: "OnPropTransmit"

**Comment by arthurdead** [comment]
you need to use my fork of sendproxy and your sourcemod was outdated
